# Generated by Django 5.2.8 on 2025-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
